### ISSUE TITLE
ValueError: Can't load save_path when it is None.

### ISSUE THREAD

**Issue by emanhamed** [anuragranj/coma#12]
I trained the model using the command stated in the readme file and when I'm trying to test, I'm getting this error:
``
  File "main.py", line 96, in <module>
    predictions, loss = model.predict(X_test, X_test)
  File "/media/eman/HDD/SecondYear/NewComa/coma-trained/lib/models.py", line 29, in predict
    sess = self._get_session(sess)
  File "/media/eman/HDD/SecondYear/NewComa/coma-trained/lib/models.py", line 328, in _get_session
    self.op_saver.restore(sess, filename)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1557, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.
``

**Comment by anuragranj** [comment]
While training using
`python main.py --data data/sliced --name <NAME>`
You need to make sure this file exists: `checkpoints/<NAME>/checkpoint`,
and when you open this file it should points to your saved model before calling:
`python main.py --data data/sliced --name <NAME> --mode test`

**Comment by emanhamed** [comment]
I have the checkpoints folder already and inside it, there are 12 folders for the different expressions and another folder called sliced that has a file called checkpoint.txt and the models. 

Isn't it supposed to be that way?

**Comment by anuragranj** [comment]
The sliced folder was provided with the code and it has the pretrained model. You should save your training using a different `-name`.
