### ISSUE TITLE
The Euclidean error

### ISSUE THREAD

**Issue by Archer666** [anuragranj/coma#15]
Excuse me，The Euclidean error of mesh was calculated in the paper, and the Errors are in millimeters, but the CoMA dataset downloaded from http://coma.is.tue.mpg.de/ is apparently not in millimeters.So I want to know the the transformation between the two scales

**Comment by anuragranj** [comment]
here is the code to do the necessary scale transformations and compute the errors. This will reproduce the numbers in the paper.
https://github.com/anuragranj/coma/blob/master/computeErrors.py
