### ISSUE TITLE
Did you trained 12 models for 12 kinds of expression?

### ISSUE THREAD

**Issue by havefunbb** [anuragranj/coma#34]
Found there are 12 folders in the ./checkpoints folder, and each folder corresponds to an expression.  Why? I just thought that there should only be one trained model which was trained by all the meshes of all expressions? Am I wrong?

**Comment by anuragranj** [comment]
They are for cross validation. Each model is trained on all but X expression, where X is the model name. The particular model is tested on X expression.

**Comment by havefunbb** [comment]
Nice idea

**Comment by ligungun** [comment]
Run the following script. The models are slightly better (~1% on average) than ones reported in the paper.
sh generateErrors.sh

But I got very bad results
such as ：bareteeth PCA Error: 1.952+1.883 | 1.330  CoMA Error: 6.805+5.611 | 5.374
                  cheeks_in PCA Error: 1.852+1.902 | 1.180  CoMA Error: 5.642+4.033 | 4.670
