### ISSUE TITLE
What do I have to consider for using larger and more complex data?

### ISSUE THREAD

**Issue by EJShim** [anuragranj/coma#36]
Hello, I made a simple visualization for testing face autoencoder : [https://www.youtube.com/watch?v=PGeEPXblCI4&ab_channel=EJShim](https://www.youtube.com/watch?v=PGeEPXblCI4&ab_channel=EJShim)

And I am currently trying to use more complex data, which is randomly-transformed 16 teeth model.

It has totally 73316 points (face model have 5023 points).

CoMA somehow optimizes them, but the results seem very noisy compared to the face model :

![image](https://user-images.githubusercontent.com/8189976/105506088-041e8880-5d0d-11eb-9c86-80c058ad8493.png)

Is the data too large or too much transformed?

Or, do you think this kind of data can be used? If so, what do I have to consider for improving results?

**Comment by anuragranj** [comment]
Here is a project that uses coma-like model for a more complex clothing generation application. This considers some more things for improving results for the complex cases. 
https://github.com/QianliM/CAPE
