### ISSUE TITLE
Training on a different template

### ISSUE THREAD

**Issue by emanhamed** [anuragranj/coma#4]
I have been trying to retrain your model on a different template (different 3D mesh of different topology) but unfortunately, I'm failing due to the different number of vertices and different connectivity pattern from the raw data. Is it possible to do this type of retraining and if yes, what needs to be changed? 

Thanks for help

**Comment by anuragranj** [comment]
As long as all your training samples are aligned to the same template, it should work. You just need to specify a template mesh for it here, using any of your mesh files:

https://github.com/anuragranj/coma/blob/643b23474659743b13839a05818873256464df2a/main.py#L37
