### ISSUE TITLE
psbody.mesh module not found issue

### ISSUE THREAD

**Issue by bharathvarma008** [anuragranj/coma#6]
While running the process.py script, in order to read all the objects from a particular folder and save it as numpy arrays, got the following error.

    python processData.py --data /clothed_output/ --save_path /clothed_out_nparray/

    Traceback (most recent call last):
      File "processData.py", line 3, in <module>
        from facemesh import *
      File "/home/bharath/Desktop/mesh/coma-master/facemesh.py", line 4, in <module>
        from psbody.mesh import Mesh, MeshViewer, MeshViewers
    ImportError: No module named psbody.mesh

**Comment by anuragranj** [comment]
You would need to install the mesh package from here:
https://github.com/MPI-IS/mesh

**Comment by bharathvarma008** [comment]
> You would need to install the mesh package from here:
> https://github.com/MPI-IS/mesh

Thanks Anurag! 

It worked. I missed this step while setting up the environment.

**Comment by x2z2x2x2** [comment]
> You would need to install the mesh package from here:
> https://github.com/MPI-IS/mesh

Is there anyway way to install this under windows?

**Comment by airfri** [comment]
Is there anyway way to install this under windows?

**Comment by karan00713** [comment]
Do you mean the mesh folder inside this repo [](https://github.com/MPI-IS/mesh) alone? or the whole repo

**Comment by Zorig2** [comment]
> Is there anyway way to install this under windows?

how to install this on windows 10. My "Make all" command give me error:

      0 [main] sh 18196 sync_with_child: child 4236(0x1E0) died before initialization with status code 0xC0000142
     90 [main] sh 18196 sync_with_child: *** child state waiting for longjmp
/usr/bin/sh: fork: Resource temporarily unavailable
make: *** [all] Error 128
