### ISSUE TITLE
About mesh data real size

### ISSUE THREAD

**Issue by QianyiWu** [anuragranj/coma#8]
Hi, Anurag,

Thanks for this excellent work about 3D face at first.

I have a question about your released dataset. I find in your ECCV paper, you compared Euclidean distance with other methods and errors are in millimeters. But seems released dataset forget to mention measurement units. Would you mind sharing it?

**Comment by anuragranj** [comment]
All the mesh data is in metres. You can reproduce the numbers using [coma/compareModels.py](https://github.com/anuragranj/coma/blob/master/compareModels.py).
