### ISSUE TITLE
Regarding network learning faces also

### ISSUE THREAD

**Issue by veronica1428** [anuragranj/coma#9]
Hi Anurag,

Thanks for producing this work online. Great work indeed.

I was working on this project. Is it possible that the network can learn faces also apart from vertices. Since here the mesh is being reconstructed using the reference mesh faces. If we somehow need to denoise some data from mesh in the output, for that reason I require the network should also learn faces.

Is it possible from your point of view and if yes then what type of mathematical operations (like chebyshev etc) should be applied over faces.

Waiting for your response

Regards
Veronica

**Comment by anuragranj** [comment]
This could be considerably tricky. At present, the faces (mesh faces as opposed to human faces)  are represented using a big sparse adjacency matrix **A**. This matrix can be trainable, and in theory the connections can be regressed. However, in practice, regressing all the entries of this matrix is not computationally feasible. One can, in principle, regress only certain entries of **A**, by introducing a hard constraint on the sparsity and those entries can define if the connection between two vertices is active or not.

Moreover, if you are working on 3D data, there can be many possible set of faces, given a set of vertices that define a good structure. So, its easier to set the topology (have a fixed number of faces) and move the vertices around to regress to a particular shape.

These are my two cents. Hope its helpful.
